variable "staging_project_id" {
  description = "GCP project ID for the staging environment"
  type        = string
}

variable "prod_project_id" {
  description = "GCP project ID for the production environment"
  type        = string
}

variable "cicd_runner_project_id" {
  description = "GCP project ID where CI/CD runners execute"
  type        = string
}

variable "region" {
  description = "GCP region for resource deployment"
  type        = string
  default     = "us-central1"
}

variable "repository_name" {
  description = "GitHub repository name"
  type        = string
}

variable "repository_owner" {
  description = "GitHub repository owner"
  type        = string
}

variable "create_repository" {
  description = "Whether to create the GitHub repository"
  type        = bool
  default     = false
}

variable "agent_engine_id" {
  description = "The deployed AGENT_ENGINE_ID value generated by the deploy_agents.py script for Frontend ingestion"
  type        = string
  default     = "unset"

  validation {
    condition     = can(regex("^projects/[0-9]+/locations/[a-z0-9-]+/reasoningEngines/[0-9]+$", var.agent_engine_id)) || var.agent_engine_id == "unset"
    error_message = "agent_engine_id must be a valid Vertex AI Reasoning Engine resource name (projects/{number}/locations/{region}/reasoningEngines/{id}) or 'unset' for initial setup."
  }
}

variable "project_number" {
  description = "GCP project number"
  type        = string
}
