variable "staging_project_id" {
  description = "GCP project ID for the staging environment"
  type        = string
}

variable "prod_project_id" {
  description = "GCP project ID for the production environment"
  type        = string
  default     = ""
}

variable "cicd_runner_project_id" {
  description = "GCP project ID where CI/CD pipelines execute"
  type        = string
}

variable "region" {
  description = "GCP region for resource deployment"
  type        = string
  default     = "us-central1"
}

variable "host_connection_name" {
  description = "Name of the existing Cloud Build V2 connection"
  type        = string
}

variable "repository_name" {
  description = "GitHub repository name"
  type        = string
}

variable "repository_owner" {
  description = "GitHub repository owner"
  type        = string
}

variable "create_repository" {
  description = "Whether to create the GitHub repository"
  type        = bool
  default     = false
}

variable "agent_engine_id" {
  description = "The deployed AGENT_ENGINE_ID value generated by deploy_agents.py"
  type        = string
  default     = "unset"

  validation {
    condition     = can(regex("^projects/[0-9]+/locations/[a-z0-9-]+/reasoningEngines/[0-9]+$", var.agent_engine_id)) || var.agent_engine_id == "unset"
    error_message = "agent_engine_id must be a valid Vertex AI Reasoning Engine resource name or 'unset'."
  }
}

variable "project_number" {
  description = "GCP project number (deprecated - auto-fetched)"
  type        = string
  default     = ""
}

variable "oauth_client_id_secret_name" {
  description = "Secret Manager secret name containing OAuth client credentials"
  type        = string
  default     = ""
}

variable "ge_app_staging" {
  description = "Gemini Enterprise App ID for staging"
  type        = string
  default     = ""
}

variable "ge_app_prod" {
  description = "Gemini Enterprise App ID for production"
  type        = string
  default     = ""
}

variable "agents_region" {
  description = "Region for Gemini Enterprise agents"
  type        = string
  default     = "global"
}

variable "auth_id" {
  description = "The ID of the Gemini Enterprise authorization account"
  type        = string
  default     = "a2a_langgraph_oauth_token_v4"
}

variable "app_sa_roles" {
  description = "Roles to assign to the application service account"
  type        = list(string)
  default = [
    "roles/aiplatform.user",
    "roles/discoveryengine.editor",
    "roles/logging.logWriter",
    "roles/cloudtrace.agent",
    "roles/storage.objectAdmin",
    "roles/serviceusage.serviceUsageConsumer",
  ]
}

variable "cicd_roles" {
  description = "Roles to assign to the CICD runner SA in the CICD project"
  type        = list(string)
  default = [
    "roles/storage.admin",
    "roles/aiplatform.user",
    "roles/discoveryengine.editor",
    "roles/logging.logWriter",
    "roles/cloudtrace.agent",
    "roles/artifactregistry.writer",
    "roles/cloudbuild.builds.builder",
    "roles/cloudbuild.connectionViewer",
    "roles/serviceusage.serviceUsageAdmin",
    "roles/run.admin",
  ]
}

variable "cicd_sa_deployment_required_roles" {
  description = "Roles to assign to the CICD runner SA for staging/prod projects"
  type        = list(string)
  default = [
    "roles/iam.serviceAccountUser",
    "roles/aiplatform.user",
    "roles/storage.admin",
    "roles/secretmanager.secretAccessor",
    "roles/secretmanager.viewer",
    "roles/serviceusage.serviceUsageAdmin",
    "roles/resourcemanager.projectIamAdmin",
    "roles/run.admin",
  ]
}
