steps:
  - name: "python:3.12-slim"
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv --user && uv sync --locked
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  - name: "python:3.12-slim"
    id: unit-tests
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv run pytest tests/unit
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

logsBucket: gs://${PROJECT_ID}-a2a-multiagent-lg-cicd-logs/build-logs
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
